### ISSUE TITLE
Cannot import pysam on OSX

### ISSUE THREAD

**Issue by kyleabeauchamp** [pysam-developers/pysam#231]
I think there's something fishy going on with the new htslib  HTTP support that's preventing me from importing on OSX + Anaconda python 2.7.  This is using the latest master of pysam.

The build completes successfully, but I can't import due to shared library issues:

```
ImportError: dlopen(~/anaconda2/lib/python2.7/site-packages/pysam-0.8.5-py2.7-macosx-10.5-x86_64.egg/pysam/libchtslib.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: ~/anaconda2/lib/python2.7/site-packages/pysam-0.8.5-py2.7-macosx-10.5-x86_64.egg/pysam/libchtslib.so
  Reason: Incompatible library version: libchtslib.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

**Comment by kyleabeauchamp** [comment]
I tried to do the obvious things like `export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"` and `export HAVE_LIBCURL=False` but then I end up with errors at build time:


```
htslib/hfile_libcurl.c:632:2: error: No HMAC() routine found by configure
#error No HMAC() routine found by configure
 ^
htslib/hfile_libcurl.c:890:30: error: use of undeclared identifier 'DIGEST_BUFSIZ'
        unsigned char digest[DIGEST_BUFSIZ];
                             ^
htslib/hfile_libcurl.c:891:29: warning: implicit declaration of function 's3_sign' is invalid in C99 [-Wimplicit-function-declaration]
        size_t digest_len = s3_sign(digest, &secret, message);
```

**Comment by kyleabeauchamp** [comment]
So I finally got this to work on my mac, but it was a fairly major challenge.  

I was able to modify setup.py to force the "conservative" build options by modifying line 243 to be a dummy `if True` statement and then also disabling libcurl via `export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"`.    It turns out I had to do *both* of those things to fully disable the CURL support and override the issue with a too-old version of libcurl.

**Comment by AndreasHeger** [comment]
Apologies the build failed, and many thanks for a solution. I think I ran into a similar issue before. I will check this again - time to change laptops...

**Comment by kyleabeauchamp** [comment]
I also opened a pull request on bioconda-recipes to debug building pysam 0.8.5 on the bioconda build system.  My goal there is to identify any build issues before the 0.8.5 release so that we can build a conda package smoothly.  Here is the link.  I'm finding similar linker issues there as well.  

https://github.com/bioconda/bioconda-recipes/pull/843

**Comment by kyleabeauchamp** [comment]
On a related note, we have a working `bioconda` recipe for htslib 1.3 (https://github.com/bioconda/bioconda-recipes/tree/master/recipes/htslib).  That brings up the question of which way to embed the htslib library for the bioconda pysam recipe.  

Is it worth trying to build the pysam recipe in "HTSLIB_MODE=external" with the externally built htslib via conda?   I guess my goal is to follow your "best practices" recommendation.

**Comment by pgrosu** [comment]
Hi Kyle,

You might be interested in a previous post I wrote at the following link:

https://github.com/ga4gh/server/issues/335#issuecomment-183752681

Hope it helps,
Paul

**Comment by kyleabeauchamp** [comment]
Presumably when we release a bioconda package, we want to get the libcurl functionality working?  AFAIK that was one of the key enhancements in the latest htslib, so we presumably want to get that working on both OSX and linux.

**Comment by jmarshall** [comment]
> Reason: Incompatible library version: libchtslib.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

These libcurl version numbers are not burnt into pysam or htslib in any way, so you must have two copies of libcurl.so in various places on your machine.  The more up-to-date one (dylib version 9.0.0) was used when you built pysam, but it was not available (not even via $DYLD_LIBRARY_PATH) when you tried to import it.

**Comment by kyleabeauchamp** [comment]
I do have two copies on my machine, one from OSX and one from Anaconda python.  I agree that the issue is controlling the versions.  

I have been able to get pysam to build and run by setting DYLD_LIBRARY_PATH to point to my anaconda/lib directory during both compile and run time.  However, this is not the recommended behavior for running anaconda, as it tries to manage library loading via rpath instead of using environment variables.

**Comment by kyleabeauchamp** [comment]
So yeah, I think part of the issue here is ensuring that the libraries during compile are the same as during loading.

**Comment by AndreasHeger** [comment]
Hi @kyleabeauchamp 

> I was able to modify setup.py to force the "conservative" build options by modifying line 243 to be a dummy if True statement and then also disabling libcurl via export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl". It turns out I had to do both of those things to fully disable the CURL support and override the issue with a too-old version of libcurl. 

This has been fixed by c3a3f9e86c32b042ecdacf8ae2a7ddc3212b05d1

Now, specifiying --disable-libcurl will remove hfile_libcurl.c from sources to be included.

**Comment by AndreasHeger** [comment]
Pull requests #234 and #240 should have taken care of this.

Closing for now.

**Comment by martinfthomsen** [comment]
Hi I'm trying to use pysam, but I still get this error, how has this been fixed? and what can I do to make it work?

    $ export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"
    $ export HAVE_LIBCURL=False
    $ pip install pysam
    Collecting pysam
    Installing collected packages: pysam
    Successfully installed pysam-0.9.1
    $ python -c "import pysam"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Applications/anaconda/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
        from pysam.libchtslib import *
    ImportError: dlopen(/Applications/anaconda/lib/python3.5/site-packages/pysam/libchtslib.cpython-35m-darwin.so, 2): Library not loaded: libcurl.4.dylib
      Referenced from: /Applications/anaconda/lib/python3.5/site-packages/pysam/libchtslib.cpython-35m-darwin.so
      Reason: Incompatible library version: libchtslib.cpython-35m-darwin.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

I have also tried to set any LD path I could find referenced in several forums, but to no avail:

    LD_LIBRARY_PATH="/Applications/anaconda/lib/"
    DYLD_LIBRARY_PATH="/Applications/anaconda/lib/"
    LD_FALLBACK_LIBRARY_PATH="/Applications/anaconda/lib/"
    DYLD_FALLBACK_LIBRARY_PATH="/Applications/anaconda/lib/"

**Comment by bioinfocao** [comment]
I have just run into the same problem and solved by uninstall pysam and reinstall it with conda:
$conda install -c bioconda pysam=0.9.1
This works for me. (Mac OS X 10.11.5 )

**Comment by martinfthomsen** [comment]
Thank you, that totally fixed it for me too.

**Comment by BEFH** [comment]
this issue is back for me
