### ISSUE TITLE
pip install pysam error

### ISSUE THREAD

**Issue by thkitapci** [pysam-developers/pysam#262]
Hi, 
I am trying to install pysam with pip I have Python 2.7.11 :: Anaconda 2.5.0 (64-bit)

when I run pip install pysam I get the following output

Collecting pysam
  Using cached pysam-0.9.0.tar.gz
Building wheels for collected packages: pysam
  Running setup.py bdist_wheel for pysam: started
[?25l  Running setup.py bdist_wheel for pysam: finished with status 'error'
  Complete output from command /home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Lg2cSy/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpIL7lClpip-wheel- --python-tag cp27:
  # pysam: htslib mode is shared
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking for ranlib... ranlib
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for stdlib.h... (cached) yes
  checking for unistd.h... (cached) yes
  checking for sys/param.h... yes
  checking for getpagesize... yes
  checking for working mmap... yes
  checking for gmtime_r... yes
  checking for zlib.h... yes
  checking for inflate in -lz... yes
  checking for curl_easy_pause in -lcurl... yes
  checking for CCHmac... no
  checking for library containing HMAC... -lcrypto
  configure: creating ./config.status
  config.status: creating config.mk
  config.status: creating config.h
  config.status: config.h is unchanged
  # pysam: htslib configure options: --enable-libcurl
  # pysam: libcurl of builtin htslib has been enabled, adding shared libcurl and libcrypto
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pysam
  copying pysam/samtools.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/namedtuple.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/bcftools.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/utils.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/__init__.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/version.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/Pileup.py -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/config.py -> build/lib.linux-x86_64-2.7/pysam
  creating build/lib.linux-x86_64-2.7/pysam/include
  copying pysam/include/__init__.py -> build/lib.linux-x86_64-2.7/pysam/include
  package init file 'htslib/__init__.py' not found (or not a regular file)
  package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
  package init file 'samtools/__init__.py' not found (or not a regular file)
  package init file 'bcftools/__init__.py' not found (or not a regular file)
  package init file 'samtools/win32/__init__.py' not found (or not a regular file)
  copying pysam/cfaidx.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/cvcf.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/csamfile.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/calignedsegment.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/cutils.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/ctabixproxies.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/cbcf.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/chtslib.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/ctabix.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/calignmentfile.pxd -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/tabix_util.h -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/samfile_util.h -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/pysam_util.h -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/htslib_util.h -> build/lib.linux-x86_64-2.7/pysam
  copying pysam/pysam_stream.h -> build/lib.linux-x86_64-2.7/pysam
  creating build/lib.linux-x86_64-2.7/pysam/include/htslib
  copying htslib/version.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
  copying htslib/config.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
  copying htslib/hts_internal.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
  copying htslib/hfile_internal.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
  creating build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/vcf_sweep.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/kfunc.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/synced_bcf_reader.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/hfile.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/hts.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/kseq.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/cram.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/ksort.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/regidx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/klist.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/khash.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/knetfile.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/faidx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/tbx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/kstring.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/hts_defs.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/vcf.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/vcfutils.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/khash_str2int.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/kbitset.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/sam.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  copying htslib/htslib/bgzf.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
  creating build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/samtools.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam_tview.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/sample.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam_lpileup.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/kprobaln.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/version.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/sam_opts.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam2bcf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam_plbuf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/errmod.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/stats_isize.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/sam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/bam_endian.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/sam_header.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  copying samtools/pysam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
  creating build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/call.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/prob1.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/ploidy.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/rbuf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/version.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/kmin.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/khash_str2str.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/filter.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/vcmp.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/HMM.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/tsv2vcf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/bcftools.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/gvcf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/convert.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  copying bcftools/pysam.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
  creating build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
  copying samtools/win32/xcurses.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
  copying samtools/win32/zconf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
  copying samtools/win32/zlib.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
  running build_ext
  skipping 'pysam/chtslib.c' Cython extension (up-to-date)
  building 'pysam.libchtslib' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/pysam
  creating build/temp.linux-x86_64-2.7/htslib
  creating build/temp.linux-x86_64-2.7/htslib/cram
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c pysam/chtslib.c -o build/temp.linux-x86_64-2.7/pysam/chtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c pysam/htslib_util.c -o build/temp.linux-x86_64-2.7/pysam/htslib_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile_net.c -o build/temp.linux-x86_64-2.7/htslib/hfile_net.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/synced_bcf_reader.c -o build/temp.linux-x86_64-2.7/htslib/synced_bcf_reader.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/vcfutils.c -o build/temp.linux-x86_64-2.7/htslib/vcfutils.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile.c -o build/temp.linux-x86_64-2.7/htslib/hfile.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile_libcurl.c -o build/temp.linux-x86_64-2.7/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
  htslib/hfile_libcurl.c: In function ‘easy_errno’:
  htslib/hfile_libcurl.c:93: error: ‘CURLE_NOT_BUILT_IN’ undeclared (first use in this function)
  htslib/hfile_libcurl.c:93: error: (Each undeclared identifier is reported only once
  htslib/hfile_libcurl.c:93: error: for each function it appears in.)
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pysam
[?25h  Running setup.py clean for pysam
Failed to build pysam
Installing collected packages: pysam
  Running setup.py install for pysam: started
[?25l    Running setup.py install for pysam: finished with status 'error'
    Complete output from command /home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Lg2cSy/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iZdIhk-record/install-record.txt --single-version-externally-managed --compile:
    # pysam: htslib mode is shared
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for curl_easy_pause in -lcurl... yes
    checking for CCHmac... no
    checking for library containing HMAC... -lcrypto
    configure: creating ./config.status
    config.status: creating config.mk
    config.status: creating config.h
    config.status: config.h is unchanged
    # pysam: htslib configure options: --enable-libcurl
    # pysam: libcurl of builtin htslib has been enabled, adding shared libcurl and libcrypto
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pysam
    copying pysam/samtools.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/namedtuple.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/bcftools.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/utils.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/__init__.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/version.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/Pileup.py -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/config.py -> build/lib.linux-x86_64-2.7/pysam
    creating build/lib.linux-x86_64-2.7/pysam/include
    copying pysam/include/__init__.py -> build/lib.linux-x86_64-2.7/pysam/include
    package init file 'htslib/__init__.py' not found (or not a regular file)
    package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
    package init file 'samtools/__init__.py' not found (or not a regular file)
    package init file 'bcftools/__init__.py' not found (or not a regular file)
    package init file 'samtools/win32/__init__.py' not found (or not a regular file)
    copying pysam/cfaidx.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/cvcf.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/csamfile.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/calignedsegment.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/cutils.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/ctabixproxies.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/cbcf.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/chtslib.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/ctabix.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/calignmentfile.pxd -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/tabix_util.h -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/samfile_util.h -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/pysam_util.h -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/htslib_util.h -> build/lib.linux-x86_64-2.7/pysam
    copying pysam/pysam_stream.h -> build/lib.linux-x86_64-2.7/pysam
    creating build/lib.linux-x86_64-2.7/pysam/include/htslib
    copying htslib/version.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
    copying htslib/config.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
    copying htslib/hts_internal.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
    copying htslib/hfile_internal.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib
    creating build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcf_sweep.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/kfunc.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/synced_bcf_reader.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/hfile.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/hts.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/kseq.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/cram.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/ksort.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/regidx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/klist.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/khash.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/knetfile.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/faidx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/tbx.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/kstring.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/hts_defs.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcf.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/vcfutils.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/khash_str2int.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/kbitset.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/sam.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    copying htslib/htslib/bgzf.h -> build/lib.linux-x86_64-2.7/pysam/include/htslib/htslib
    creating build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/samtools.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam_tview.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/sample.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam_lpileup.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/kprobaln.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/version.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/sam_opts.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam2bcf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam_plbuf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/errmod.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/stats_isize.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/sam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/bam_endian.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/sam_header.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    copying samtools/pysam.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools
    creating build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/call.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/prob1.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/ploidy.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/rbuf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/version.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/kmin.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/khash_str2str.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/filter.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/vcmp.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/HMM.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/tsv2vcf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/bcftools.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/gvcf.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/convert.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    copying bcftools/pysam.h -> build/lib.linux-x86_64-2.7/pysam/include/bcftools
    creating build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
    copying samtools/win32/xcurses.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
    copying samtools/win32/zconf.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
    copying samtools/win32/zlib.h -> build/lib.linux-x86_64-2.7/pysam/include/samtools/win32
    running build_ext
    skipping 'pysam/chtslib.c' Cython extension (up-to-date)
    building 'pysam.libchtslib' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/pysam
    creating build/temp.linux-x86_64-2.7/htslib
    creating build/temp.linux-x86_64-2.7/htslib/cram
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c pysam/chtslib.c -o build/temp.linux-x86_64-2.7/pysam/chtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c pysam/htslib_util.c -o build/temp.linux-x86_64-2.7/pysam/htslib_util.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile_net.c -o build/temp.linux-x86_64-2.7/htslib/hfile_net.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/synced_bcf_reader.c -o build/temp.linux-x86_64-2.7/htslib/synced_bcf_reader.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/vcfutils.c -o build/temp.linux-x86_64-2.7/htslib/vcfutils.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile.c -o build/temp.linux-x86_64-2.7/htslib/hfile.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/include/python2.7 -c htslib/hfile_libcurl.c -o build/temp.linux-x86_64-2.7/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    htslib/hfile_libcurl.c: In function ‘easy_errno’:
    htslib/hfile_libcurl.c:93: error: ‘CURLE_NOT_BUILT_IN’ undeclared (first use in this function)
    htslib/hfile_libcurl.c:93: error: (Each undeclared identifier is reported only once
    htslib/hfile_libcurl.c:93: error: for each function it appears in.)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Lg2cSy/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iZdIhk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Lg2cSy/pysam
[?25h

I'll appreciate the help!

Thanks
Hamdi

**Comment by Bratdaking** [comment]
This problem is related to htslib and is I think solved upstream. However you can try this to use a manual install of htslib, by setting the environmental settings:
HTSLIB_LIBRARY_DIR to point to the htslib/lib folder
and
HTSLIB_INCLUDE_DIR to point to the htslib/include folder

Unfortunately there is an issue in the setup.py script, when you do so, that complains that the tabixproxies cannot locate the htslib. In a minute I will upload a patch that solves that issue.

**Comment by thkitapci** [comment]
Hi,
I have installed htslib and set the environment variables as you suggested. I am getting the exact same error what I did is 

I set those 2 environmental variables (I use the bash shell)
HTSLIB_LIBRARY_DIR=htslib/lib
HTSLIB_INCLUDE_DIR=htslib/include/

then I executed

pip install pysam 

I am getting the same error

Thanks!

**Comment by thkitapci** [comment]
As far as I understand pysam is supposed to install htslib within when I call 

pip install pysam 

is there an different way to install pysam ? I just tried this on a different machine (running Ubuntu 14.04.4 LTS and Python 2.7.11 :: Anaconda 2.5.0 (64-bit)) and I am getting the same error. Can there be a problem in the pip install pysam command for the latest release ? I used pip to install pysam about 6-7 months ago without any problem.

Thanks
Hamdi

**Comment by kyleabeauchamp** [comment]
If you are using anaconda, there is a version available on bioconda (bioconda.github.io) installable via:

```
conda install -c bioconda pysam
```

**Comment by thkitapci** [comment]
Thanks a lot! This solved the problem. Actually I just remember that this is how I installed sometime ago. I think it would be a good idea to put this instruction on pysam's installation guide, I think a lot of people using pysam will be using anaconda. 

I am able to import pysam but is there a function or sample data set to check if the package is installed correctly ? Something like 

>>>import pysam
>>>pysam.test() 

??

Hamdi

**Comment by kyleabeauchamp** [comment]
I don't think so.  The tests don't come with the pysam package, you have to download the source repo, then generate the test data, then run the nose tests.

**Comment by jsmedmar** [comment]
I'm alsoSame error on a Red Hat machine. This means that I should reinstall htslib?

**Comment by wspoonr** [comment]
I fixed this on Centos 6.7 by updating libcurl, see http://serverfault.com/questions/321321/upgrade-curl-to-latest-on-centos

**Comment by AndreasHeger** [comment]
Thanks. This has been patched in htslib. I have now manually applied the patch to the htslib
version in pysam.

**Comment by jsmedmar** [comment]
I upgraded curl to version `7.48.0` but it didn't fix my installation issue.  What specific version of htslib is required?

**Comment by Bratdaking** [comment]
Hey all,
Has been patched but not yet released, so pip install will not work yet. The current workaround, for people that cannot install libcurl, is to install htslib (1.3) manually. Remember the location. Set the two environment variables:
HTSLIB_LIBRARY_DIR to point to the htslib/lib folder
and
HTSLIB_INCLUDE_DIR to point to the htslib/include folder
and add the htslib/lib folder to your LD_LIBRARY_PATH (sorry I forget to mention that in my earlier post). Get a recent checkout of the pysam master branch, and build it yourself (do not forget to install cython first) by giving the next command in the source folder:
python setup.py install
(you might want to add --user or --prefix to set different install locations).

**Comment by AndreasHeger** [comment]
I will try to release a new version of pysam this week that should address the two main installation problems of pysam (py3 and libcurl).

**Comment by fankatt** [comment]
Thanks the help from all, especiall Bratdaking, finally, I successfully complied pysam for python 3.4.
I will summarize here what I had struggled and provided some tips for who else experienced the pain:
1. don't use pip, instead, compiling it manually.
2. install htslib manually, and export the path for HTSLIB_LIBRARY_DIR, HTSLIB_INCLUDE_DIR, and LD_LIBRARY_PATH as Bratdaking said.
3. I changed one line in setup.py: HTSLIB_MODE = "shared"  is changed to HTSLIB_MODE = "external". BTW, my pysam version is 0.9.0
4. When you are compling pysam, there might be an error like " samtools/bam_tview_curses.c.pysam.c:28:20: fatal error: config.h: No such file or directory". Simple create an empty file: touch samtools/config.h.  See https://github.com/pysam-developers/pysam/issues/257.

That's what I did with it. Hope it will be helpful for others.

**Comment by kkshaxqd** [comment]
pysam problem, change the pysam version from 0.9.0 to 0.9.1  will resolve it . pip install pysam==0.9.1

**Comment by transcript** [comment]
Changing pysam version didn't fix this for me (clean install, Ubuntu 14.04, python2.7).  

```
htslib/hfile_libcurl.c:630:2: error: #error No HMAC() routine found by configure

 #error No HMAC() routine found by configure

  ^

htslib/hfile_libcurl.c: In function ‘add_s3_settings’:

htslib/hfile_libcurl.c:888:30: error: ‘DIGEST_BUFSIZ’ undeclared (first use in this function)

         unsigned char digest[DIGEST_BUFSIZ];

                              ^

htslib/hfile_libcurl.c:888:30: note: each undeclared identifier is reported only once for each function it appears in

htslib/hfile_libcurl.c:889:9: warning: implicit declaration of function ‘s3_sign’ [-Wimplicit-function-declaration]

         size_t digest_len = s3_sign(digest, &secret, message);

         ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
