### ISSUE TITLE
0.11.0 build failure with missing symbols

### ISSUE THREAD

**Issue by nieder** [pysam-developers/pysam#443]
Building 0.11.0 on OS X with htslib1.4 leads to missing symbols when linking libcsamtools.so:
~~~~
gcc -L/sw/lib -L/sw/lib/python2.7/config -lpython2.7 -L/sw/lib -L/sw/lib -MD -I/sw/include build/temp.macosx-10.11-x86_64-2.7/pysam/libcsamtools.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam2bcf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam2bcf_indel.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam2depth.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_addrprg.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_aux.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_cat.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_color.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_flags.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_import.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_index.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_lpileup.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_mate.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_md.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_plbuf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_plcmd.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_quickcheck.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_reheader.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_rmdup.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_rmdupse.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_sort.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_split.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bam_stat.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bamshuf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bamtk.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bedcov.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/bedidx.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/cut_target.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/dict.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/faidx.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/padding.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/phase.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sam.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sam_header.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sam_opts.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sam_utils.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sam_view.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/sample.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/stats.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/samtools/stats_isize.c.pysam.o -Lpysam -L/sw/lib -Lbuild/lib.macosx-10.11-x86_64-2.7/pysam -L/sw/lib -lz -lhts -lchtslib -o build/lib.macosx-10.11-x86_64-2.7/pysam/libcsamtools.so -dynamiclib -rpath /sw/lib/python2.7/site-packages -Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/pysam-0.11-py2.7-macosx-10.11-x86_64.egg/pysam/libcsamtools.so -Wl,-x
Undefined symbols for architecture x86_64:
  "_pysam_stderr", referenced from:
      _bcf_call_glfgen in bam2bcf.c.pysam.o
      _bcf_call_gap_prep in bam2bcf_indel.c.pysam.o
      _main_depth in bam2depth.c.pysam.o
      _usage in bam2depth.c.pysam.o
      _main_addreplacerg in bam_addrprg.c.pysam.o
      _cram_cat in bam_cat.c.pysam.o
      _bam_cat in bam_cat.c.pysam.o
      ...
  "_pysam_stdout", referenced from:
      _bam_view1 in bam.c.pysam.o
      _main_depth in bam2depth.c.pysam.o
      _main_addreplacerg in bam_addrprg.c.pysam.o
      _bam_cat in bam_cat.c.pysam.o
      _main_flags in bam_flags.c.pysam.o
      _bam_index in bam_index.c.pysam.o
      _bam_idxstats in bam_index.c.pysam.o
      ...
  "_pysam_stdout_fn", referenced from:
      _bam_fillmd in bam_md.c.pysam.o
~~~~
I have set HTSLIB_INCLUDE_DIR=/sw/include and HTSLIB_LIBRARY_DIR=/sw/lib to find my external copy of htslib-1.4.

**Comment by nieder** [comment]
'pysam/pysam_util.c' needs to be added to the source_pattern section for csamtools() and cbcftools() in setup.py.  But I'm still getting a missing `_main_header` symbol when linking libcbcftools.so
~~~~
Undefined symbols for architecture x86_64:
  "_main_reheader", referenced from:
      _cmds in main.c.pysam.o
~~~~
Will need to look fro the source later.

**Comment by nieder** [comment]
I think I found the issue w/ all the missing symbols during linking libcsamtools.so and libcbcftools.so. This is the patch I needed on pysam-0.12.0:
~~~~
diff -ruN pysam-0.12.0-orig/samtools/bam_reheader.c pysam-0.12.0/samtools/bam_reheader.c
--- pysam-0.12.0-orig/samtools/bam_reheader.c	2017-08-24 09:01:55.000000000 -0500
+++ pysam-0.12.0/samtools/bam_reheader.c	2017-09-06 22:38:27.000000000 -0500
@@ -35,6 +35,7 @@
 #include "htslib/hfile.h"
 #include "htslib/cram.h"
 #include "samtools.h"
+#include "samtools/version.h"
 
 #define BUF_SIZE 0x10000
 
@@ -512,3 +513,8 @@
 
     return -r;
 }
+
+const char *samtools_version()
+{
+    return SAMTOOLS_VERSION;
+}
diff -ruN pysam-0.12.0-orig/setup.py pysam-0.12.0/setup.py
--- pysam-0.12.0-orig/setup.py	2017-08-24 09:01:55.000000000 -0500
+++ pysam-0.12.0/setup.py	2017-09-06 22:38:01.000000000 -0500
@@ -462,7 +462,7 @@
 
 csamtools = Extension(
     "pysam.libcsamtools",
-    [source_pattern % "samtools"] +
+    [source_pattern % "samtools", "pysam/pysam_util.c"] +
     glob.glob(os.path.join("samtools", "*.pysam.c")) +
     htslib_sources +
     os_c_files,
@@ -477,12 +477,12 @@
 
 cbcftools = Extension(
     "pysam.libcbcftools",
-    [source_pattern % "bcftools"] +
+    [source_pattern % "bcftools", "pysam/pysam_util.c", "samtools/bam_reheader.c", "samtools/sam_utils.c.pysam.c"] +
     glob.glob(os.path.join("bcftools", "*.pysam.c")) +
     htslib_sources +
     os_c_files,
     library_dirs=["pysam"] + htslib_library_dirs,
-    include_dirs=["bcftools", "pysam", "."] +
+    include_dirs=["bcftools", "samtools", "pysam", "."] +
     include_os + htslib_include_dirs,
     libraries=external_htslib_libraries + internal_htslib_libraries,
     language="c",
~~~~

Does this look reasonable? Or am I completely solving this the wrong way?

**Comment by AndreasHeger** [comment]
Thanks, I think this is related to #519.

I am refactoring setup.py to make it more tractable what goes where.

**Comment by nieder** [comment]
Based on the patch in #519 it does seem to be related. Thanks for following up.

**Comment by nieder** [comment]
053ebf9 did not fix this for me. I still get the missing symbols above when building HEAD. My patch above from [Sep 6](https://github.com/pysam-developers/pysam/issues/443#issuecomment-327682610) or the patch 7a0d22d from @vorlonofportland at the top of #519 both lead to successful builds (@vorlonofportland's patch seems nicer).

**Comment by AndreasHeger** [comment]
Thanks for checking - will not merge before I get this right.

**Comment by AndreasHeger** [comment]
are you referring to #574

**Comment by AndreasHeger** [comment]
Ok, the issue is that I used extern for variables in different cython extension modules. Apparently, some compiler versions are happier with this than others.
I have now rearranged the stdout redirection so that no more extern's cross shared library boundaries, so hopefully the issue should now disappear.

**Comment by nieder** [comment]
On a fresh checkout of HEAD that includes e9d330b, the symbols _pysam_stderr, _pysam_stdout, and _pysam_stdout_fn are now resolved w/out any changes needed. However, '_main_reheader' is still unresolved when linking libcbcftools.so:
````
gcc -L/sw/lib -L/sw/lib/python2.7/config -lpython2.7 -L/sw/lib -L/sw/lib -I/sw/include build/temp.macosx-10.11-x86_64-2.7/pysam/libcbcftools.o build/temp.macosx-10.11-x86_64-2.7/bcftools/bam2bcf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/bam2bcf_indel.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/bam_sample.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/bcftools.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/bin.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/ccall.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/consensus.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/convert.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/csq.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/em.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/filter.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/gvcf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/hclust.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/HMM.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/kmin.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/main.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/mcall.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/mpileup.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/ploidy.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/prob1.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/regidx.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/smpl_ilist.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/tabix.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/tsv2vcf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfannotate.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfbuf.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfcall.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfcnv.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfconcat.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfconvert.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcffilter.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfgtcheck.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfindex.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfisec.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfmerge.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfnorm.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfplugin.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfquery.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfroh.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfsom.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfsort.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfstats.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcfview.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/vcmp.c.pysam.o build/temp.macosx-10.11-x86_64-2.7/bcftools/version.c.pysam.o -L/src/pysam-refactor/pysam -L/sw/lib -Lbuild/lib.macosx-10.11-x86_64-2.7/pysam -Lbuild/lib.macosx-10.11-x86_64-2.7/pysam -Lbuild/lib.macosx-10.11-x86_64-2.7/pysam -L/sw/lib -lz -lhts -lchtslib -o build/lib.macosx-10.11-x86_64-2.7/pysam/libcbcftools.so -dynamiclib -rpath @loader_path -Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/libcbcftools.so -Wl,-x
Undefined symbols for architecture x86_64:
  "_main_reheader", referenced from:
      _cmds in main.c.pysam.o
ld: symbol(s) not found for architecture x86_64
````

**Comment by christianbioinf** [comment]
Also for me, the current checkout of 67b5fe63387f03e3f9804f78e2cc736c9eb16c14 does not fix the undefined symbols for `_main_reheader`. This causes pyinstaller-onefile scripts to fail:
```
Traceback (most recent call last):
  File "my_script.py", line 75, in <module>
    from pysam.libcutils import *
  File "/tmp/pip-build-Y5fvcF/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pysam/__init__.py", line 7, in <module>
  File "/tmp/pip-build-Y5fvcF/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 687, in load_module
ImportError: /tmp/_MEIDQNHTI/pysam.libcbcftools.so: undefined symbol: main_reheader
[31946] Failed to execute script my_script
```

**Comment by christianbioinf** [comment]
I tracked down the issue. In `bcftools/main.c` there is a declaration of all functions available in the bcftools package including to `main_reheader` but for some reason the pysam's bcftools folder does not contain the file `reheader.c` and hence the definition of this function. By simply including this file and its variant `reheader.c.pysam.c`, the issue disappears.

On another note, could you also add the import of `pysam.libctabixproxies` to `pysam/__init__.py` since it is the only one missing there and I always need to manually import it in order to avoid import errors.

**Comment by AndreasHeger** [comment]
Thanks. The reheader file was excluded as the symbol is identical with main_reheader in samtools. I think this caused an issue in the past, but seems to work now.

Added imports of pysam.libctabixproxies to __init__.py

What I am surprised is that I don't get these missing symbols issues in my build environment.

**Comment by AndreasHeger** [comment]
Pushed. Will not close this issue until somebody can confirm all the missing symbols are covered.
Thanks for tracking this done.

**Comment by christianbioinf** [comment]
The missing symbols are fixed but with the current HEAD ba80ddd9f682df409e4393e085d34317d2e5dce0 I get the following error message for compiling a cython extension containing pysam.
```
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import pysam
  File "venv/lib/python2.7/site-packages/pysam/__init__.py", line 47, in <module>
    ["SamtoolsError"] +\
AttributeError: 'module' object has no attribute '__all__'
```
It appears to be due to the fact that the statement `import pysam.libctabixproxies as libctabixproxies` is currently commented out but it is still included with `libctabixproxies.__all__ +\` in the `__all__ = \` statement. After removing this line, it works for me.

**Comment by nieder** [comment]
On OS X at ba80ddd, I can also successfully build pysam w/out any missing symbols or other errors.

**Comment by AndreasHeger** [comment]
Thanks @christianbioinf  and @nieder .

The tabproxies issue is now also gone and will now close this issue.

**Comment by dinvlad** [comment]
I'm still having this issue with Pyinstaller 3.5 (on Python 2.7). My current workaround is to use
`--hiddenimport pysam.libctabixproxies` option for pyinstaller.
